version: '3.8'

services:
  server:
    image: node:20
    container_name: DEV-opt-delivery-server
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - ./data/:/app-data/
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run start:dev"
    env_file:
      - .env